### ISSUE TITLE
Pinging users with a space in their username

### ISSUE THREAD

**Issue by Skillmon** [topanswers/topanswers#6] opened 2020-01-16 21:23 UTC
When pinging a user who's got a space in his name by clicking on his avatar in chat, it only adds the first word of the name after the `@` and leaves the rest of the name out.

1. Go to a chat room with an active user who's got a space in the username
2. Click on that user's avatar

I'd expect to get the whole user name inserted after the `@` with all spaces removed.

![ping-bug](https://user-images.githubusercontent.com/8701017/72563731-94322280-38ae-11ea-82dc-0d21ad2d37ff.png)

 - OS: Arch Linux
 - Browser: Firefox
 - Version: 72.0-1 (Arch repositories)

**Comment by jackdouglas** [comment] 2020-01-16 23:05
This is by design — so I'm closing this issue as 'not a bug'. Of course please raise it on meta as a feature request if you'd like to see it changed.

The idea behind the 'feature' is that I can be "Jack Douglas", but pinged as "Jack" similar to normal speech. An user can choose to be pinged by their full name by having no spaces of course, but I prefer to usually be addressed by my first name.

Also, thanks for using the new issue tracker here!

**Closed by jackdouglas** 2020-01-16 23:05 UTC
Labels: bug

**Comment by Skillmon** [comment] 2020-01-16 23:13
@jackdouglas And I thought it was strange to ping one who doesn't use his real name as "@Strong" instead of "@StrongMad". But I totally understand your preferences. This might not scale well though, suppose you have a really common name, like for example "Jack", and there are 1000 users who are named "Jack"...

**Comment by jackdouglas** [comment] 2020-01-17 12:14
> This might not scale well though, suppose you have a really common name, like for example "Jack", and there are 1000 users who are named "Jack"...

Only the particular 'Jack' that you actually pinged will get the notification though, so I don't think that is a problem — the '@Jack' that gets added to the comment is just optional eye-candy, the actual ID of the user you are pinging or replying to is passed to the server when you post your message.

**Comment by alerque** [comment] 2020-01-17 12:16
@Skillmon I believe in this case the actual ping code and the text display of `@name` are entirely disconnected. You can even ping without including the `@` at all, and you can write whatever `@bogusfoo` you like without pinging anybody. This is also by design, although I personally think it is a bad design choice. This might be one to re-open for discussion on meta. The combination of non-unique changeable display names and pings is hard to reconcile, but the existing pretend-match is really confusing and I agree it will not scale well. Perhaps ditching the use of `@name` text entirely would help.
