### ISSUE TITLE
Image upload button omscures chat input field

### ISSUE THREAD

**Issue by abrudz** [topanswers/topanswers#40] opened 2020-02-25 11:35 UTC
![image](https://user-images.githubusercontent.com/10961427/75244020-e118eb00-57c2-11ea-94f2-6e9c92392057.png)
![image](https://user-images.githubusercontent.com/10961427/75244053-efff9d80-57c2-11ea-9a46-f8066c2cb66f.png)

**Comment by dajare** [comment] 2020-02-25 20:50
A duplicate of #39. :wink:

**Closed** 2020-02-25 23:11 UTC
Labels: bug
